In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_excel("C:/Users/黃柏倫/Desktop/data/python project/大盤指數盤後數據.xlsx",header=0)

In [4]:
x=[]
y=[]
for i in range(len(df.index)-10):
    x.append(list(df.loc[i:i+9]['收盤價']))
    y.append(df.漲跌平[i+10])
x=np.array(x).reshape(len(x),10,1)

In [5]:
x[0]

array([[123.28],
       [122.93],
       [122.51],
       [121.94],
       [121.13],
       [122.04],
       [122.41],
       [122.38],
       [121.88],
       [123.03]])

In [6]:
y

[0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 -1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 1.0,
 -1.0,
 -1.0,
 -1.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 -1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 -1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 -1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 -1.0,
 -1.0,
 1.0,
 -1.0,
 -1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 -1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 -1.0,
 -1.0,
 1.0,
 -1.0,
 1.0,
 1.0,
 -1.0,
 -1.0,
 -1.0,
 1.0,
 -1.0,
 1.0,
 -1.0,
 0.0,
 -1.0,
 1.0,
 0.0,
 -1.0,
 -1.0,
 0.0,


In [7]:
from keras.utils import np_utils

Using TensorFlow backend.


In [8]:
x_train=x[:10000]
x_test=x[10000:]
y = np_utils.to_categorical(y, 3)
y_train=y[:10000]
y_test=y[10000:]

In [9]:
y_train

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]], dtype=float32)

In [10]:
from keras.models import Sequential
from keras.layers import Dense, Embedding
from keras.layers import LSTM

In [15]:
model = Sequential()
model.add(LSTM(40, input_shape=(10,1)))
model.add(Dense(3, activation='softmax'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_2 (LSTM)                (None, 40)                6720      
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 123       
Total params: 6,843
Trainable params: 6,843
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.compile(loss='binary_crossentropy',optimizer="adam",metrics=['acc'])#,validation)

In [17]:
model.fit(x_train, y_train,batch_size=1000,epochs=5)

Epoch 1/5
10000/10000 [==============================] - 3s 259us/step - loss: 0.7794 - acc: 0.5618
Epoch 2/5
10000/10000 [==============================] - 1s 107us/step - loss: 0.7183 - acc: 0.5618
Epoch 3/5
10000/10000 [==============================] - 1s 97us/step - loss: 0.6709 - acc: 0.6120
Epoch 4/5
10000/10000 [==============================] - 1s 88us/step - loss: 0.6471 - acc: 0.6665
Epoch 5/5
10000/10000 [==============================] - 1s 99us/step - loss: 0.6426 - acc: 0.6667


In [18]:
model.evaluate(x_test, y_test)

3144/3144 [==============================] - 1s 189us/step


[0.6362527032541562, 0.6666666865348816]

# normalize

In [19]:
dfc=np.array(df['收盤價'])
dfc-= dfc.min()
dfc =dfc/dfc.max()

In [21]:
x=[]
y=[]
for i in range(len(df.index)-10):
    x.append(dfc[i:i+10])
    y.append(df.漲跌平[i+10])
x=np.array(x).reshape((len(x),10,1))
y=np.array(y).reshape((len(y),1))

In [22]:
from keras.utils import np_utils

In [23]:
x_train=x[:10000]
x_test=x[10000:]
y = np_utils.to_categorical(y, 3)
y_train=y[:10000]
y_test=y[10000:]

In [24]:
y_train[2]

array([0., 1., 0.], dtype=float32)

In [25]:
from keras.models import Sequential
from keras.layers import Dense, Embedding
from keras.layers import LSTM

In [30]:
model1 = Sequential()

model1.add(LSTM(40, input_shape=(10,1)))
model1.add(Dense(3, activation='softmax'))
model1.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_4 (LSTM)                (None, 40)                6720      
_________________________________________________________________
dense_4 (Dense)              (None, 3)                 123       
Total params: 6,843
Trainable params: 6,843
Non-trainable params: 0
_________________________________________________________________


In [31]:
model1.compile(loss='binary_crossentropy',optimizer="adam",metrics=['acc'])#,validation)

In [32]:
model1.fit(x_train, y_train,batch_size=1000,epochs=5)

Epoch 1/5
10000/10000 [==============================] - 3s 267us/step - loss: 0.6359 - acc: 0.6667
Epoch 2/5
10000/10000 [==============================] - 1s 98us/step - loss: 0.6348 - acc: 0.6667
Epoch 3/5
10000/10000 [==============================] - 1s 90us/step - loss: 0.6341 - acc: 0.6667
Epoch 4/5
10000/10000 [==============================] - 1s 86us/step - loss: 0.6339 - acc: 0.6667
Epoch 5/5
10000/10000 [==============================] - 1s 88us/step - loss: 0.6339 - acc: 0.6667


In [33]:
model1.evaluate(x_test, y_test)

3144/3144 [==============================] - 1s 268us/step


[0.6596060117692438, 0.6666666865348816]

# API 

In [55]:
def nor(t):
    t-= t.min()
    t =t/t.max()
    return t

In [57]:
dfc=nor(np.array(df['收盤價']))
dfv=nor(np.array(df['成交值']))

In [62]:
a=[]
b=[]
y=[]
for i in range(len(df.index)-10):
    a.append(dfc[i:i+10])
    b.append(dfv[i:i+10])
    y.append(df.漲跌平[i+10])
a=np.array(a).reshape(len(x),10,1)
b=np.array(b).reshape(len(y),10,1)

In [63]:
b[0]

array([[3.06313426e-05],
       [1.22525370e-05],
       [3.36944769e-05],
       [4.28838796e-05],
       [3.06313426e-05],
       [1.22525370e-05],
       [1.53156713e-05],
       [1.22525370e-05],
       [1.28651639e-04],
       [3.06313426e-05]])

In [65]:
from keras.utils import np_utils

In [66]:
a_train=a[:10000]
a_test=a[10000:]
b_train=b[:10000]
b_test=b[10000:]
yc = np_utils.to_categorical(y, 3)
y_train=yc[:10000]
y_test=yc[10000:]

In [67]:
y_train

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]], dtype=float32)

In [68]:
from keras.models import Sequential
from keras.layers import Dense, Embedding
from keras.layers import LSTM

In [69]:
from keras.models import Model
from keras.layers import Input
from keras.layers import concatenate, add

In [70]:
f_1 = LSTM(40, input_shape=(10,1))
g_1 = LSTM(40, input_shape=(10,1))

h_1 = Dense(3, activation='softmax')

In [71]:
a0 = Input(shape=(10,1))
b0 = Input(shape=(10,1))
a1 = f_1(a0)

b1 = g_1(b0)


u = concatenate([a1,b1])

y = h_1(u)

In [74]:
model3 = Model([a0,b0], y)
model3.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_5 (InputLayer)            (None, 10, 1)        0                                            
__________________________________________________________________________________________________
input_6 (InputLayer)            (None, 10, 1)        0                                            
__________________________________________________________________________________________________
lstm_7 (LSTM)                   (None, 40)           6720        input_5[0][0]                    
__________________________________________________________________________________________________
lstm_8 (LSTM)                   (None, 40)           6720        input_6[0][0]                    
__________________________________________________________________________________________________
concatenat

In [76]:
model3.compile(loss='binary_crossentropy',optimizer="adam",metrics=['acc'])#,validation)

In [77]:
model3.fit([a_train,b_train], y_train,batch_size=1000,epochs=5)

Epoch 1/5
10000/10000 [==============================] - 11s 1ms/step - loss: 0.6363 - acc: 0.6667
Epoch 2/5
10000/10000 [==============================] - 2s 198us/step - loss: 0.6350 - acc: 0.6667 0s - loss: 0.6351 - acc: 0.66
Epoch 3/5
10000/10000 [==============================] - 2s 201us/step - loss: 0.6342 - acc: 0.6667 0s - loss: 0.6343 - acc: 0.666
Epoch 4/5
10000/10000 [==============================] - 2s 188us/step - loss: 0.6339 - acc: 0.6667 1s - loss: 0.6346 - acc:
Epoch 5/5
10000/10000 [==============================] - 2s 190us/step - loss: 0.6340 - acc: 0.6667


In [78]:
model3.evaluate([a_test,b_test], y_test)

3144/3144 [==============================] - 1s 462us/step


[0.6588945918107457, 0.6666666865348816]